update rcS_neutrino_hd51

diff --git a/root/release/rcS_neutrino_hd51 b/root/release/rcS_neutrino_hd51
--- a/root/release/rcS_neutrino_hd51
+++ b/root/release/rcS_neutrino_hd51
@@ -1,6 +1,8 @@
 #!/bin/sh
 
 . /etc/profile
+echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
+SYSDATE=`date +"%Y%m%d"`
 
 read model < /etc/model
 
@@ -16,82 +18,106 @@ mount -t proc proc /proc
 mount -t sysfs sys /sys
 mount -t tmpfs tmp /tmp
 mount -t tmpfs media /media
-mount -t tmpfs mnt /mnt
 mkdir -p /dev/pts
 mount -t devpts devpts /dev/pts
-echo /sbin/mdev >/proc/sys/kernel/hotplug
-mdev -s
 
-echo "starting interface"
+echo "[rcS] starting mountall"
 /etc/init.d/mountall start
 
+if [ -e /var/backup_flash.tar.gz ]; then
+	tar xvf /var/backup_flash.tar.gz -C /
+	rm -f /var/backup_flash.tar.gz
+fi
+
+# load moduls from modules.extra ( kerneloptions )
+[ -f /var/etc/modules.extra ] && eval `awk '{ if ($1) print "insmod /lib/modules/" $1 ".ko " $2,$3,$4,$5,$6,$7,$8,$9 "; "}' < /var/etc/modules.extra`
+
+echo "[rcS] setup network"
+NFS=$(grep -c nfs /proc/cmdline)
+if [ "$NFS" -eq "1" ]; then
+	echo "Booting from nfs, don't set network"
+elif [ -e /var/tuxbox/config/.bootargs ]; then
+	echo "using ip set via bootargs, don't reset network"
+else
+	if [ -e /etc/network/interfaces ]; then
+		ip addr flush eth0
+		/etc/init.d/networking stop
+		#DHCP=$(grep -c dhcp /etc/network/interfaces)
+		#if [ "$DHCP" -eq "1" ]; then
+		#	echo "Starting dhcp"
+		#	/etc/init.d/udhcpc start
+		#fi
+		/etc/init.d/networking start
+	fi
+fi
+/sbin/ifconfig lo 127.0.0.1 up
+
+# get net-time
+(ntpd -n -q -p time.fu-berlin.de) &
+
+/etc/init.d/hostname start
+/etc/init.d/portmap start
+/usr/sbin/inetd
+# rpc.statd for nfs
+/etc/init.d/nfs-common start
+
+echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` load modules"
 insmod /lib/modules/hd51_1.ko
 insmod /lib/modules/hd51_2.ko
 insmod /lib/modules/hd51_3.ko
 insmod /lib/modules/hd51_4.ko
 
-if [ -e /var/backup_flash.tar.gz ]; then
-  tar xvf /var/backup_flash.tar.gz -C /
-  rm -f /var/backup_flash.tar.gz
-fi
-
 echo "Booting... DDT" > /dev/dbox/oled0
 
-echo "setup network"
-/etc/init.d/hostname start
-/etc/init.d/portmap start
-/usr/sbin/inetd
-NFS=$(grep -c nfs /proc/cmdline)
-  if [ "$NFS" -eq "1" ]; then
-    echo "Booting from nfs, don't set network"
-    elif [ -e /var/tuxbox/config/.bootargs ]; then
-    echo "using ip set via bootargs, don't reset network"
-  else
-    if [ -e /etc/network/interfaces ]; then
-      ip addr flush eth0
-      /etc/init.d/networking stop
-      DHCP=$(grep -c dhcp /etc/network/interfaces)
-      if [ "$DHCP" -eq "1" ]; then
-        echo "Starting dhcp"
-        /etc/init.d/udhcpc start
-      fi
-      /etc/init.d/networking start
-    fi
-  fi
-/sbin/ifconfig lo 127.0.0.1 up
+echo "[rcS] starting mdev"
+# avoid mdev actions until cmds is ready
+[ "$AUTOFS" == "1" ] && touch /tmp/.cmds-start
+echo /sbin/mdev >/proc/sys/kernel/hotplug
 
 # set dummy time
-date -s "2017-01-01 00:00"
+NTPDATE=`date +"%Y%m%d"`
+if [ "$SYSDATE" == "$NTPDATE" ];then
+	date -s "2017-01-01 00:00"
+	#date -s "200901011200"
+	echo "no ntp-date"
+	killall -9 ntpd
+	rm -f /tmp/ntpd.pid
+else
+	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
+	rm -f /tmp/ntpd.pid
+fi
+
 
 until false
 do
-    echo "starting GUI ->"
-    chmod 755 /usr/local/bin/*
-    if [ -e /tmp/neutrino ]; then
-      chmod 755 /tmp/neutrino
-      /tmp/neutrino
-    else
-      /usr/local/bin/neutrino -v 0
-    fi
-    rtv=$?
-    echo "GUI ended <- RTV: " $rtv
-    case "$rtv" in
-      0) echo "0"
-        echo "SHUTDOWN"
-      init 0;;
-      1) echo "1"
-        echo "REBOOT"
-        echo "      *-*       " > /dev/dbox/oled0
-      init 6;;
-      3) echo "3"
-        echo "RESTART"
-        echo "    RESTART     " > /dev/dbox/oled0
-      sync;;
-      *) echo "*"
-        echo -e "\033[01;31mERROR: $rtv\033[00m"
-        echo "    *ERROR*     " > /dev/dbox/oled0
-      init 6;;
-    esac
+	echo "[rcS] starting GUI ->"
+	chmod 755 /usr/local/bin/*
+	if [ -e /tmp/neutrino ]; then
+		chmod 755 /tmp/neutrino
+		/tmp/neutrino
+	else
+		/usr/local/bin/neutrino -v 0
+	fi
+	rtv=$?
+	echo "GUI ended <- RTV: " $rtv
+	case "$rtv" in
+		0) echo "$rtv"
+			echo "SHUTDOWN"
+			init 0;;
+		1) echo "$rtv"
+			echo "REBOOT"
+			echo "      *-*       " > /dev/dbox/oled0
+			init 6;;
+		3) echo "$rtv"
+			echo "RESTART"
+			echo "    RESTART     " > /dev/dbox/oled0
+			sync;;
+		*) echo "*"
+			echo -e "\033[01;31mERROR: $rtv\033[00m"
+			echo "    *ERROR*     " > /dev/dbox/oled0
+			#init 6
+			;;
+	esac
 done
 echo "      *-*       " > /dev/dbox/oled0
 
@@ -99,4 +125,3 @@ echo "      *-*       " > /dev/dbox/oled0
 echo "REBOOT $model" > /dev/dbox/oled0
 echo "REBOOT $model"
 reboot -f
-
